config/routes.rb
# frozen_string_literal: true

# config/routes.rb

Rails.application.routes.draw do
  get 'lottery/index'
  post 'lottery/index', to: 'lottery#upload_csv'
  root 'lottery#index'
  get 'download_csv', to: 'lottery#download_csv', as: 'download_csv'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/lottery_controller.rb
# frozen_string_literal: true

require 'csv'
# app/controllers/lottery_controller.rb
class LotteryController < ApplicationController
  before_action :lottery_files, only: :index

  def index; end

  def upload_csv
    winning_number = params[:winning_number]
    uploaded_file = params[:csv_file]

    return unless uploaded_file

    csv_text = uploaded_file.read
    result = LotteryProcessor.process_and_save_csv(csv_text, winning_number)

    if result
      flash[:notice] = result[:csv_path]
      @winners = result[:winners]
    end

    render :index
  end

  def download_csv
    file_path = Rails.root.join('tmp', params[:filename])

    if File.exist?(file_path)
      send_file file_path, disposition: 'attachment'
    else
      flash[:alert] = 'File not found.'
      redirect_to root_path
    end
  end

  private

  def lottery_files
    @lottery_files ||= Dir[Rails.root.join('tmp', 'lottery_results_*.csv')]
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/lottery_helper.rb
# frozen_string_literal: true

module LotteryHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LcsLotteryApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice].present? %>
      <div class="alert alert-success">
        <%= flash[:notice] %>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/lottery/_csv_file_list.html.erb
<div class="card">
  <div class="card-header">
    Download CSV Files
  </div>
  <div class="card-body">
    <ul class="list-group">
      <% @lottery_files.each do |csv_file| %>
        <li class="list-group-item">
          <%= link_to File.basename(csv_file), download_csv_path(filename: File.basename(csv_file)) %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/lottery/_form.html.erb
<%= form_with(url: lottery_index_path, method: "post", local: true, multipart: true, class: "mt-4") do |form| %>
  <div class="form-group">
    <%= form.label :csv_file, "Upload CSV File:" %>
    <%= form.file_field :csv_file, class: "form-control-file", required: true %>
  </div>

  <div class="form-group">
    <%= form.label :winning_number, "Winning Number:" %>
    <%= form.text_field :winning_number, class: "form-control", required: true %>
  </div>

  <div class="text-center">
    <%= form.submit "Calculate Winnings", class: "btn btn-primary mt-1" %>
  </div>
<% end %>

app/views/lottery/_winners_table.html.erb
<h2 class="mt-5">Winners</h2>
<table class="table">
  <thead>
    <tr>
      <th>Participant</th>
      <th>Credits</th>
    </tr>
  </thead>
  <tbody>
    <% @winners.each do |winner| %>
      <tr>
        <td><%= winner[0] %></td>
        <td><%= winner[1] %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/lottery/index.html.erb
<h1 class="text-center">Lottery Results</h1>
<div class="container mt-5">
  <div class="row">

    <% if @lottery_files.present? %>
      <div class="col-md-4">
        <%= render 'csv_file_list' %>
      </div>
    <% end %>

    <div class="col-md-8">
      
      <%= render 'form' %>
      <% if @winners.present? %>
        <%= render 'winners_table' %>
      <% else %>
        <p class="mt-5 text-center">No winners found.</p>
      <% end %>
    </div>
  </div>
</div>